version: 3

includes:
  tofu:
    taskfile: tofu
    aliases: ["tofu"]
  k0s:
    taskfile: k0s
    aliases: ["k0s"]
tasks:
  apply:
    desc: "Create the cluster from scratch"
    cmds:
      - task: tofu:init
      - task: tofu:plan
      - task: tofu:apply
      - task: tofu:output
      - task: k0s:apply
      - task: k0s:kubeconfig
  destroy:
    desc: "Destroy the cluster"
    cmds:
      - task: k0s:reset
      - task: tofu:destroy