version: 3

tasks:
  apply:
    dir: k0s
    desc: Apply the k0s configuration to the cluster (i.e create or update the cluster)
    cmds:
     - k0sctl apply
  kubeconfig:
    dir: k0s
    desc: Save the kubeconfig to ~/.kube/
    cmds:
      # TODO: make templateable
      - k0sctl kubeconfig > $KUBECONFIG
  reset:
    dir: k0s
    desc: Reset the k0s cluster (e.g. reset nodes to factory settings but don't delete them)
    cmds:
      - k0sctl reset  --force